#!/usr/bin/env python3
"""Emit the deck's geometry for the web, so the browser draws the printed card.

The rosette packing, the ring radii and the back's emblem are all worked out
in deck.py already, and re-deriving any of it in ClojureScript would be a
second implementation to keep in step with the first.  So this computes the
placements once, here, and ships them as data: the client only has to draw.

Everything is in *cut* card units -- 750 x 1050, the same space deck.py lays
out in -- so an SVG with that viewBox is the card at any size.
"""
import json
import math
import pathlib
import sys

HERE = pathlib.Path(__file__).parent
sys.path.insert(0, str(HERE))
import deck as D

OUT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1
                   else HERE.parent / "resources" / "public" / "universe" / "deck.json")

PATHS = json.loads((HERE / "shapes" / "paths.json").read_text())
POINTS = {}
for name, d in PATHS.items():
    v = [float(x) for x in d.replace("M", " ").replace("L", " ")
         .replace("Z", " ").replace(",", " ").split()]
    POINTS[name] = list(zip(v[0::2], v[1::2]))


def rosette(shape, n, table):
    """Where the n copies go, in units of one copy's enclosing radius, and how
    far the whole arrangement reaches.  Lifted verbatim from make_pyramid.py so
    the web card and the printed card are packed identically."""
    t = table[f"{shape}:{n}"]
    base = 0.0 if n == 1 else t / math.sin(math.pi / n)
    places, reach = [], 0.0
    for k in range(n):
        phi = 360.0 * k / n
        rad = math.radians(phi)
        cx, cy = base * math.sin(rad), -base * math.cos(rad)
        places.append([round(phi, 4), round(cx, 5), round(cy, 5)])
        cos, sin = math.cos(rad), math.sin(rad)
        for px, py in POINTS[shape]:
            rx, ry = px * cos - py * sin, px * sin + py * cos
            reach = max(reach, math.hypot(rx + cx, ry + cy))
    return {"places": places, "reach": round(reach, 5)}


def back():
    """The emblem, as deck.render_back builds it: four green eyes inside, a
    gold ring, then twelve of the other three shapes alternating yellow and
    purple.  Every symbol lands on a copy of itself under a half turn."""
    L = D.LAYOUT
    w, h = 750, 1050
    cx, cy = w / 2.0, h / 2.0
    outer = L["field_d"] / 2 * 1.04
    ring_r = outer / (1 + math.sin(math.pi / 12))
    rho = ring_r * math.sin(math.pi / 12) * 0.92
    gap = ring_r - rho / 0.92
    inner = gap * 0.90
    r_in = inner / (1 + math.sin(math.pi / 4))
    rho_in = r_in * math.sin(math.pi / 4) * 0.94

    marks = []
    for k, name in enumerate(["pyramid", "star", "helix"] * 4):
        phi = 360.0 * k / 12
        marks.append({"shape": name,
                      "color": ["yellow", "purple"][k % 2],
                      "phi": round(phi, 4),
                      "x": round(cx + ring_r * math.sin(math.radians(phi)), 4),
                      "y": round(cy - ring_r * math.cos(math.radians(phi)), 4),
                      "r": round(rho, 4)})
    for k in range(4):
        phi = 360.0 * k / 4
        marks.append({"shape": "eye", "color": "green", "phi": round(phi, 4),
                      "x": round(cx + r_in * math.sin(math.radians(phi)), 4),
                      "y": round(cy - r_in * math.cos(math.radians(phi)), 4),
                      "r": round(rho_in, 4)})
    return {"ground": "#191324",
            "ring": {"cx": cx, "cy": cy, "r": round(gap, 4),
                     "width": 4.0, "color": D.COLORS["yellow"]},
            "marks": marks}


def main():
    table = D.ring_table()
    L = D.LAYOUT
    out = {
        "note": "generated by universe/make_web.py -- do not edit",
        "card": {"width": 750, "height": 1050},
        "colors": D.COLORS,
        "colorOrder": D.COLOR_ORDER,
        "shapes": D.SHAPES,
        "paths": PATHS,
        "field": {"cx": 375, "cy": 525, "d": L["field_d"]},
        "rosettes": {f"{s}:{n}": rosette(s, n, table)
                     for s in D.SHAPES for n in D.NUMBERS},
        # the index block: the number, then the shape beneath it.  A second
        # copy turned 180 degrees goes in the opposite corner, so the card
        # reads either way up.
        "corner": {
            "x": L["margin_x"] + L["index_w"] / 2,
            "numberBaseline": L["margin_y"] + L["num_cap"],
            "numberCap": L["num_cap"],
            "glyphCx": L["margin_x"] + L["index_w"] / 2,
            "glyphCy": L["margin_y"] + L["num_cap"] + L["num_gap"] + L["glyph_d"] / 2,
            "glyphR": L["glyph_d"] / 2,
        },
        "back": back(),
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(out, separators=(",", ":")) + "\n")
    kb = OUT.stat().st_size / 1024
    print(f"  {OUT}  {kb:.0f} KB  "
          f"{len(out['rosettes'])} rosettes, {len(out['back']['marks'])} marks on the back")


if __name__ == "__main__":
    main()
