"""Universal topology generator: produces board graphs from parameters.

A tiling is generated by (base_type, size, symmetry, boundary, modifier).
The existing topologies (square, hex, ring) are special cases:
  square grid  = regular("square", size=5, boundary="finite")
  hex grid     = regular("hex", size=4, boundary="finite")
  torus hex    = regular("hex", size=4, boundary="torus")
  ring board   = radial(symmetry=5, rings=5)
  triangle grid = regular("triangle", size=4, boundary="finite")

Modifiers transform a base tiling:
  staircase(step=1)  — each row adds `step` extra columns
  holes(positions)   — remove specific nodes
  asymmetric(ratio)  — stretch one axis

All generators produce the same Topology output as topology.py.
"""

from __future__ import annotations
import math
from dataclasses import dataclass, field

from .topology import Topology


# ── Regular tilings ───────────────────────────────────────────────────────────

def _regular_square(size: int, wrap: bool = False) -> Topology:
    """Square tiling (4.4.4.4). 4-connected grid."""
    n = size * size
    nodes = list(range(n))
    adj: dict[int, list[int]] = {}
    coords: dict[int, tuple[int, int]] = {}
    for r in range(size):
        for c in range(size):
            idx = r * size + c
            coords[idx] = (r, c)
            neighbors = []
            for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                nr, nc = r + dr, c + dc
                if wrap:
                    nr, nc = nr % size, nc % size
                if 0 <= nr < size and 0 <= nc < size:
                    neighbors.append(nr * size + nc)
            adj[idx] = neighbors
    return Topology(name=f"square_{size}", nodes=nodes, adjacencies=adj,
                    coords=coords, grid_size=size)


def _regular_hex(radius: int, wrap: bool = False) -> Topology:
    """Hexagonal tiling (6.6.6). 6-connected axial coordinates."""
    cells = sorted([(q, r) for q in range(-radius + 1, radius)
                    for r in range(-radius + 1, radius)
                    if abs(q + r) < radius])
    cell_to_id = {c: i for i, c in enumerate(cells)}
    nodes = list(range(len(cells)))
    hex_dirs = [(1, 0), (-1, 0), (0, 1), (0, -1), (1, -1), (-1, 1)]
    adj = {}
    for (q, r), idx in cell_to_id.items():
        neighbors = []
        for dq, dr in hex_dirs:
            nc = (q + dq, r + dr)
            if nc in cell_to_id:
                neighbors.append(cell_to_id[nc])
            elif wrap:
                # Simple toroidal wrapping for hex
                wq = (nc[0] + radius) % (2 * radius - 1) - (radius - 1)
                wr = (nc[1] + radius) % (2 * radius - 1) - (radius - 1)
                wc = (wq, wr)
                if wc in cell_to_id:
                    neighbors.append(cell_to_id[wc])
        adj[idx] = neighbors
    grid_size = 2 * radius - 1
    coords = {cell_to_id[c]: (c[1] + radius - 1, c[0] + radius - 1) for c in cells}
    return Topology(name=f"hex_{radius}", nodes=nodes, adjacencies=adj,
                    coords=coords, grid_size=grid_size)


def _regular_triangle(size: int, wrap: bool = False) -> Topology:
    """Triangular tiling (3.3.3.3.3.3). 6-connected triangular grid.

    Uses offset coordinates where each cell is a triangle.
    Row r, col c: upward triangle if (r+c) even, downward if odd.
    Each triangle has 3 edge-neighbors plus 3 vertex-neighbors = 6 total.
    For simplicity, we use edge-neighbors only (3-connected).
    """
    # Each row has `size` triangles, alternating up/down
    # Total rows = size
    n = size * size
    nodes = list(range(n))
    adj: dict[int, list[int]] = {}
    coords: dict[int, tuple[int, int]] = {}

    for r in range(size):
        for c in range(size):
            idx = r * size + c
            coords[idx] = (r, c)
            neighbors = []
            upward = (r + c) % 2 == 0

            # Same-row neighbors (left and right)
            if c > 0 or wrap:
                nc = c - 1 if c > 0 else size - 1
                neighbors.append(r * size + nc)
            if c < size - 1 or wrap:
                nc = (c + 1) % size
                neighbors.append(r * size + nc)

            # Vertical neighbor (depends on orientation)
            if upward:
                # Upward triangle connects to downward triangle below
                nr = r + 1
                if nr < size or wrap:
                    nr = nr % size
                    neighbors.append(nr * size + c)
            else:
                # Downward triangle connects to upward triangle above
                nr = r - 1
                if nr >= 0 or wrap:
                    nr = nr % size
                    neighbors.append(nr * size + c)

            adj[idx] = neighbors

    return Topology(name=f"triangle_{size}", nodes=nodes, adjacencies=adj,
                    coords=coords, grid_size=size)


# ── Radial topologies ─────────────────────────────────────────────────────────

def _radial(symmetry: int, num_rings: int, notches: bool = True) -> Topology:
    """Radial/ring topology (like Organism). Reuses existing build_ring."""
    from .topology import build_ring
    return build_ring(symmetry, num_rings, notches)


# ── Modifiers ─────────────────────────────────────────────────────────────────

def _apply_staircase(topo: Topology, step: int) -> Topology:
    """Remove nodes to create a staircase pattern. Each row r removes
    nodes in columns > (base_cols - r * step)."""
    if step <= 0:
        return topo
    # Find grid dimensions from coords
    max_row = max(r for r, c in topo.coords.values())
    max_col = max(c for r, c in topo.coords.values())

    remove_nodes = set()
    for node, (r, c) in topo.coords.items():
        cutoff = max_col - r * step
        if c > cutoff:
            remove_nodes.add(node)

    return _remove_nodes(topo, remove_nodes, f"{topo.name}_stair{step}")


def _apply_holes(topo: Topology, hole_fraction: float, seed: int = 42) -> Topology:
    """Remove a fraction of nodes randomly (avoiding disconnection)."""
    import random as rng
    rng_state = rng.getstate()
    rng.seed(seed)

    n_remove = max(1, int(len(topo.nodes) * hole_fraction))
    # Don't remove more than 30% to avoid disconnection
    n_remove = min(n_remove, len(topo.nodes) // 3)

    candidates = list(topo.nodes)
    rng.shuffle(candidates)
    remove_nodes = set(candidates[:n_remove])

    rng.setstate(rng_state)
    return _remove_nodes(topo, remove_nodes, f"{topo.name}_holes")


def _apply_asymmetric(topo: Topology, extra_cols: int) -> Topology:
    """Extend the board by adding extra columns on one side."""
    if extra_cols <= 0:
        return topo
    max_row = max(r for r, c in topo.coords.values()) + 1
    max_col = max(c for r, c in topo.coords.values()) + 1
    new_grid_size = max(max_row, max_col + extra_cols)

    # Add new nodes
    next_id = max(topo.nodes) + 1
    new_nodes = list(topo.nodes)
    new_adj = dict(topo.adjacencies)
    new_coords = dict(topo.coords)

    for r in range(max_row):
        for c in range(max_col, max_col + extra_cols):
            node_id = next_id
            next_id += 1
            new_nodes.append(node_id)
            new_coords[node_id] = (r, c)
            neighbors = []
            # Connect to left neighbor
            left_nodes = [n for n, (nr, nc) in new_coords.items()
                          if nr == r and nc == c - 1]
            for ln in left_nodes:
                neighbors.append(ln)
                new_adj.setdefault(ln, []).append(node_id)
            # Connect to above/below
            for dr in [-1, 1]:
                nr = r + dr
                above_nodes = [n for n, (nrr, nc) in new_coords.items()
                               if nrr == nr and nc == c]
                for an in above_nodes:
                    neighbors.append(an)
                    new_adj.setdefault(an, []).append(node_id)
            new_adj[node_id] = neighbors

    return Topology(name=f"{topo.name}_asym{extra_cols}",
                    nodes=new_nodes, adjacencies=new_adj,
                    coords=new_coords, grid_size=new_grid_size)


def _remove_nodes(topo: Topology, remove: set[int], name: str) -> Topology:
    """Remove nodes and clean up adjacencies."""
    nodes = [n for n in topo.nodes if n not in remove]
    adj = {}
    for n in nodes:
        adj[n] = [nb for nb in topo.adjacencies.get(n, []) if nb not in remove]
    coords = {n: topo.coords[n] for n in nodes if n in topo.coords}
    return Topology(name=name, nodes=nodes, adjacencies=adj,
                    coords=coords, grid_size=topo.grid_size)


# ── Tiling specification ──────────────────────────────────────────────────────

@dataclass(frozen=True)
class TilingSpec:
    """Parameters for topology generation."""
    base:      str = "hex"       # "square" | "hex" | "triangle" | "radial"
    size:      int = 4           # board size / radius / num_rings
    symmetry:  int = 4           # for radial boards
    boundary:  str = "finite"    # "finite" | "torus"
    modifier:  str = "none"      # "none" | "staircase" | "holes" | "asymmetric"
    mod_param: int = 0           # modifier parameter (step, hole_seed, extra_cols)

    def description_bits(self) -> float:
        bits = 0.0
        bits += math.log2(4)   # base type
        bits += math.log2(4)   # size (3-6)
        bits += math.log2(4)   # symmetry
        bits += 1.0            # boundary (finite/torus)
        bits += math.log2(4)   # modifier type
        if self.modifier != "none":
            bits += math.log2(4)  # mod_param
        return bits


# ── Domains for random generation ─────────────────────────────────────────────

BASE_TYPES = ["square", "hex", "triangle", "radial"]
TILING_SIZES = [3, 4, 5, 6]
SYMMETRIES = [3, 4, 5, 6]
BOUNDARIES = ["finite", "torus"]
MODIFIERS = ["none", "none", "none", "staircase", "holes", "asymmetric"]  # biased toward none
MOD_PARAMS = [0, 1, 2]


# ── Factory ───────────────────────────────────────────────────────────────────

def generate_topology(spec: TilingSpec) -> Topology:
    """Generate a topology from a tiling specification."""
    # Base topology
    wrap = spec.boundary == "torus"
    if spec.base == "square":
        topo = _regular_square(spec.size, wrap)
    elif spec.base == "hex":
        topo = _regular_hex(spec.size, wrap)
    elif spec.base == "triangle":
        topo = _regular_triangle(spec.size, wrap)
    elif spec.base == "radial":
        topo = _radial(spec.symmetry, spec.size, notches=True)
    else:
        topo = _regular_hex(spec.size, wrap)

    # Apply modifier
    if spec.modifier == "staircase" and spec.mod_param > 0:
        topo = _apply_staircase(topo, spec.mod_param)
    elif spec.modifier == "holes":
        topo = _apply_holes(topo, 0.15, seed=spec.mod_param)
    elif spec.modifier == "asymmetric" and spec.mod_param > 0:
        topo = _apply_asymmetric(topo, spec.mod_param)

    # Ensure non-empty
    if not topo.nodes:
        topo = _regular_hex(3, False)

    return topo
